%% Home single step sequence

sensorSelfCalibratorInit;

% For limbs calibration
homeCalibLimbs.labels = {...
    'ctrl','ctrl','ctrl','ctrl','ctrl','ctrl';...
    'pos','pos','pos','pos','pos','pos';
    'left_arm','right_arm','left_leg','right_leg','torso','head'};

if strcmp(partToRun,'arms')
    homeCalibLimbs.val = {...
        [-35.96 29.96 0.049 50 -7 -69 -8],...
        [-35.96 29.96 0.049 50 -7 -69 -8],...
        [0.066  0.005  0.077  -0.011  -0.011  0],...
        [0.066  0.005  0.077  -0.011  -0.011  0],...
        [0 0 0],...
        [0 0 0]};
    
    % For torso calibration
    homeCalibTorso = homeCalibLimbs;
    homeCalibTorso.val = {...
        [-30 30 -30 20 0 0 0],...
        [-30 30 -30 20 0 0 0],...
        [0 10 0 0 0 0],...
        [0 10 0 0 0 0],...
        [0 0 0],...
        [0 0 0]};
end
if strcmp(partToRun,'legs')
    homeCalibLimbs.val = {...
        [-29.7 29.8 0 45 0 0 0],...
        [-29.7 29.8 0 45 0 0 0],...
        [0  8  0  0  0  0],...
        [0  8  0  0  0  0],...
        [0 0 0],...
        [0 0 0]};
    
    % For torso calibration
    homeCalibTorso = homeCalibLimbs;
    homeCalibTorso.val = {...
        [-30 30 -30 20 0 0 0],...
        [-30 30 -30 20 0 0 0],...
        [0 10 0 0 0 0],...
        [0 10 0 0 0 0],...
        [0 0 0],...
        [0 0 0]};
end

%% Motion sequences
% (a single sequence is intended to move all defined parts synchronously,
% motions from 2 different sequences should be run asynchronously)
% each calibPart should be caibrated within a single sequence.

if strcmp(partToRun,'legs')
    
    if strcmp(robotName,'icub')
        %     define tables for each limb
        %     General Labels
        left_leg_labels= {...
            'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'    ;...
            'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'   ;...
            'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_foot_tiptoe'  ,'left_foot_heel'};
        
        right_leg_labels = {...
            'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas' , 'meas' ;...
            'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'   , 'fts'  ;...
            'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_foot_tiptoe' ,'right_foot_heel', 'right_leg_hip'};
        
    else
        
        
        % Simulation
        left_leg_labels= {...
            'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'  ;...
            'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'  ;...
            'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_foot_front'  ,'left_foot_rear'};
        
        right_leg_labels = {...
            'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas' , 'meas' ;...
            'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'   , 'fts' ;...
            'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_foot_front' ,'right_foot_rear', 'right_leg'};
        
    end
    
end

if strcmp(partToRun,'arms')
    
    left_arm_labels = {...
        'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'     ;...
        'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'      ;...
        'left_arm'          ,'left_arm'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'left_arm' };
    
    right_arm_labels = {...
        'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'    ;...
        'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'    ;...
        'right_arm'          ,'right_arm'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_arm' };
end


%% Grid sequence
% common parameters
gridBuilder = GridGeneratorWOsuspend();
acqVel = 5; transVel = 5;


% Left leg

if strcmp(partToRun,'legs')
    
    left_leg_GridParams.labels =left_leg_labels;
    %
    % {...
    %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
    %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
    %     'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_leg'  ,'left_foot','left_arm'};
    
    
    gridParams = {...
        'joint'     ,'qmin','qmax','nbInterv';...
        'l_hip_pitch', -23   , 60   , 6        ;...
        'l_hip_roll' ,6   , 45   , 6        };
    
    left_leg_GridParams.val = SensorDataAcquisition.setValFromGrid(...
        gridBuilder,gridParams,acqVel,transVel,left_leg_GridParams.labels);
    
    
    % Right leg
    
    right_leg_GridParams.labels = right_leg_labels;
    
    % {...
    %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
    %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
    %     'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_leg' ,'right_foot','right_arm'};
    
    
    
    gridParams = {...
        'joint'     ,'qmin','qmax','nbInterv';...
        'r_hip_pitch', -23   , 60   , 6        ;...
        'r_hip_roll' ,6   , 45   , 6        };
    
    right_leg_GridParams.val = SensorDataAcquisition.setValFromGrid(...
        gridBuilder,gridParams,acqVel,transVel,right_leg_GridParams.labels);
end


if strcmp(partToRun,'arms')
    % Left arm
    
    left_arm_GridParams.labels = left_arm_labels;
    
    gridParams = {...
        'joint'     ,'qmin','qmax','nbInterv';...
        'l_shoulder_pitch', -150   , 13   , 6  ;...
        'l_shoulder_roll' ,  20   , 135   , 6   };
    %     'l_elbow', 10, 85, 6}; % Modifica il codice per considerare anche questo giunto
    
    left_arm_GridParams.val = SensorDataAcquisition.setValFromGrid(...
        gridBuilder,gridParams,acqVel,transVel,left_arm_GridParams.labels);
    
    
    % Right arm
    
    right_arm_GridParams.labels = right_arm_labels;
    
    gridParams = {...
        'joint'     ,'qmin','qmax','nbInterv';...
        'r_shoulder_pitch', -150   , 13   , 6  ;...
        'r_shoulder_roll' ,  20   , 135  , 6   };
    %     'r_elbow', 10, 85, 6};  % Modifica il codice per considerare anche questo giunto
    right_arm_GridParams.val = SensorDataAcquisition.setValFromGrid(...
        gridBuilder,gridParams,acqVel,transVel,right_arm_GridParams.labels);
end


%% tz sequence

if strcmp(partToRun,'legs')
    left_leg_tzParams.labels =left_leg_labels;
    
    % {...
    %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
    %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
    %     'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_leg'  ,'left_foot','left_arm'};
    left_leg_tzParams.val = {...
        [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 70  50  -70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true     ,true                ;...
        [ 70  50  70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true                 ;...
        [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true                };
    
    
    % {...
    %     [ 90  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
    %     [ 90  50  -70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true     ,true      ,true          ;...
    %     [ 90  50  70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ,true           ;...
    %     [ 90  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ,true            };
    %
    right_leg_tzParams.labels = right_leg_labels;
    
    % {...
    %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
    %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
    %     'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_leg' ,'right_foot','right_arm'};
    
    right_leg_tzParams.val = {...
        [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true     , true ;...
        [ 70  50  -70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true     ,true    , true            ;...
        [ 70  50  70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true    , true             ;...
        [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true     , true           };
end

if strcmp(partToRun,'arms')
    
    vel = 5;
    
    % Left arm
    left_arm_tzParams.labels = left_arm_labels;
    
    left_arm_tzParams.val = {...
        [ -150      135     0     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 20         20     0     19    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ -150      135    30     19    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 20         20    30     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ -150      135    30     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 20         20     0     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ -150      135    30     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      };
    
    
    
    % Right arm
    right_arm_tzParams.labels = right_arm_labels;
    
    right_arm_tzParams.val = {...
        [ -150      135     0     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 20         20     0     19    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ -150      135    30     19    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 20         20    30     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ -150      135    30     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ 20         20     0     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
        [ -150      135    30     90    -7   -69   -8],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      };
    
end




% define sequences for limbs {1} and torso {2} calibration
seqHomeParams{1} = homeCalibLimbs;
seqHomeParams{2} = homeCalibLimbs;
% seqHomeParams{3} = homeCalibLimbs;
% seqHomeParams{4} = homeCalibLimbs;
seqEndParams     = homeCalibLimbs;

if strcmp(partToRun,'arms')
    % Map parts to sequences and params
    selector.calibedParts = {...
        'left_arm','right_arm',...
        'left_arm','right_arm' ...
        };
end
if strcmp(partToRun,'legs')
    % Map parts to sequences and params
    selector.calibedParts = {...
        'left_leg','right_leg',...
        'left_leg','right_leg' ...
        };
end
selector.calibedSensors = {...
    %     {'fts'},{'fts'},...
    %     {'fts'},{'fts'},...
    {'fts'},{'fts'},...
    {'fts'},{'fts'} ...
    };
selector.setIdx  = {1,1,2,2}; %3,3,4,4}; % max index must not exceed max index of seqHomePArams

if strcmp(partToRun,'legs')
    selector.seqParams = {...
        left_leg_GridParams,right_leg_GridParams,...
        left_leg_tzParams,right_leg_tzParams ...
        };
end
if strcmp(partToRun,'arms')
    selector.seqParams = {....
        left_arm_GridParams,right_arm_GridParams,...
        left_arm_tzParams,right_arm_tzParams ...
        };
end
