%% Home single step sequence

% For limbs calibration
homeCalibLimbs.labels = {...
    'ctrl','ctrl','ctrl','ctrl','ctrl','ctrl';...
    'pos','pos','pos','pos','pos','pos';
    'left_arm','right_arm','left_leg','right_leg','torso','head'};
homeCalibLimbs.val = {...
    [10 45 0 10 0 0 0],...
    [10 45 0 10 0 0 0],...
    [0 10 0 0 0 0],...
    [0 10 0 0 0 0],...
    [0 0 0],...
    [0 0 0]};

% For torso calibration
homeCalibTorso = homeCalibLimbs;
homeCalibTorso.val = {...
    [-30 30 -30 20 0 0 0],...
    [-30 30 -30 20 0 0 0],...
    [0 10 0 0 0 0],...
    [0 10 0 0 0 0],...
    [0 0 0],...
    [0 0 0]};

%% Motion sequences
% (a single sequence is intended to move all defined parts synchronously,
% motions from 2 different sequences should be run asynchronously)
% each calibPart should be caibrated within a single sequence.

% define tables for each limb
% General Labels
% left_leg_labels= {...
%    'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'    ;...
%    'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'   ;...
%     'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_foot_tiptoe'  ,'left_foot_heel'};
% 
% right_leg_labels = {...
%      'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas' , 'meas' ;...
%      'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'   , 'fts'  ;...
%     'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_foot_tiptoe' ,'right_foot_heel', 'right_leg_hip'};

left_arm_labels = {...
     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'     ;...
     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'      ;...
    'left_arm'          ,'left_arm'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'left_arm' };

right_arm_labels = {...
     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'    ;...
     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'    ;...
    'right_arm'          ,'right_arm'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_arm' };


% Simulation
% left_leg_labels= {...
%     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'  ;...
%     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'  ;...
%     'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_foot_front'  ,'left_foot_rear'};
% 
% right_leg_labels = {...
%     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas' , 'meas' ;...
%     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'   , 'fts' ;...
%     'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_foot_front' ,'right_foot_rear', 'right_leg'};

%% Grid sequence
% common parameters
gridBuilder = GridGeneratorWOsuspend();
acqVel = 5; transVel = 5;


% Left leg

% left_leg_GridParams.labels =left_leg_labels;
% % 
% % {...
% %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
% %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
% %     'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_leg'  ,'left_foot','left_arm'};
% 
% 
% gridParams = {...
%     'joint'     ,'qmin','qmax','nbInterv';...
%     'l_hip_pitch', -23   , 60   , 6        ;...
%     'l_hip_roll' ,6   , 45   , 6        };
% 
% left_leg_GridParams.val = SensorDataAcquisition.setValFromGrid(...
%     gridBuilder,gridParams,acqVel,transVel,left_leg_GridParams.labels);
% 
% 
% % Right leg
% 
% right_leg_GridParams.labels = right_leg_labels;
% 
% % {...
% %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
% %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
% %     'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_leg' ,'right_foot','right_arm'};
% 
% 
% 
% gridParams = {...
%     'joint'     ,'qmin','qmax','nbInterv';...
%     'r_hip_pitch', -23   , 60   , 6        ;...
%     'r_hip_roll' ,6   , 45   , 6        };
% 
% right_leg_GridParams.val = SensorDataAcquisition.setValFromGrid(...
%     gridBuilder,gridParams,acqVel,transVel,right_leg_GridParams.labels);


% Left arm

left_arm_GridParams.labels = left_arm_labels;

gridParams = {...
    'joint'     ,'qmin','qmax','nbInterv';...
    'l_shoulder_pitch', -120   , 10   , 6  ;...
    'l_shoulder_roll' ,  16   , 150   , 6   ;...
    'l_elbow', 5, 90, 6}; % Modifica il codice per considerare anche questo giunto

left_arm_GridParams.val = SensorDataAcquisition.setValFromGrid(...
    gridBuilder,gridParams,acqVel,transVel,left_arm_GridParams.labels);


% Right arm

right_arm_GridParams.labels = right_arm_labels;

gridParams = {...
    'joint'     ,'qmin','qmax','nbInterv';...
    'r_shoulder_pitch', -120   , 10   , 6  ;...
    'r_shoulder_roll' ,  16   , 150  , 6   ;...
    'r_elbow', 5, 90, 6};  % Modifica il codice per considerare anche questo giunto

right_arm_GridParams.val = SensorDataAcquisition.setValFromGrid(...
    gridBuilder,gridParams,acqVel,transVel,right_arm_GridParams.labels);


%% tz sequence
% left_leg_tzParams.labels =left_leg_labels;
% 
% % {...
% %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
% %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
% %     'left_leg'          ,'left_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'       ,'left_leg'  ,'left_foot','left_arm'};
% left_leg_tzParams.val = {...
%     [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ;...    
%     [ 70  50  -70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true     ,true                ;...    
%     [ 70  50  70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true                 ;...
%     [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true                };    
%    
% 
% % {...
% %     [ 90  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ;...    
% %     [ 90  50  -70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true     ,true      ,true          ;...    
% %     [ 90  50  70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ,true           ;...
% %     [ 90  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true      ,true            };    
% %    
% right_leg_tzParams.labels = right_leg_labels;
% 
% % {...
% %     'ctrl'               ,'ctrl'          ,'meas'     ,'meas'      ,'meas'     ,'meas'      ,'meas'     ,'meas'     ,'meas'      ,'meas'      ,'meas'      ;...
% %     'pos'                ,'vel'           ,'joint'    ,'joint'     ,'joint'    ,'joint'     ,'joint'    ,'joint'    ,'fts'       ,'fts'       ,'fts'       ;...
% %     'right_leg'          ,'right_leg'     ,'left_arm' ,'right_arm' ,'left_leg' ,'right_leg' ,'torso'    ,'head'     ,'right_leg' ,'right_foot','right_arm'};
% 
% right_leg_tzParams.val = {...
%     [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true     , true ;...    
%     [ 70  50  -70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true     ,true    , true            ;...    
%     [ 70  50  70  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true    , true             ;...
%     [ 70  50  0  -90  0  0],repmat(5,[1 6]),true      ,true      ,true      ,true      ,true      ,true      ,true      ,true     , true           };  
% 


vel = 5;

% Left arm
left_arm_tzParams.labels = left_arm_labels;

left_arm_tzParams.val = {...
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...    
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...    
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      };    
   


% Right arm
right_arm_tzParams.labels = right_arm_labels;

right_arm_tzParams.val = {...
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...    
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...    
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      ;...
    [ -120  150  0  90  0  0 0],repmat(vel,[1 7]),   true      ,true      ,true      ,true      ,true      ,true      ,true      };    






% define sequences for limbs {1} and torso {2} calibration
seqHomeParams{1} = homeCalibLimbs;
seqHomeParams{2} = homeCalibLimbs;
% seqHomeParams{3} = homeCalibLimbs;
% seqHomeParams{4} = homeCalibLimbs;
seqEndParams     = homeCalibLimbs;

% Map parts to sequences and params
selector.calibedParts = {...
%     'left_leg','right_leg',...
%     'left_leg','right_leg',...
    'left_arm','right_arm',...
    'left_arm','right_arm'
    };
selector.calibedSensors = {...
%     {'fts'},{'fts'},...
%     {'fts'},{'fts'},...
    {'fts'},{'fts'},...
    {'fts'},{'fts'}
    };
selector.setIdx  = {1,1,2,2}; %3,3,4,4}; % max index must not exceed max index of seqHomePArams
selector.seqParams = {...
%     left_leg_GridParams,right_leg_GridParams,...
%     left_leg_tzParams,right_leg_tzParams,...
    left_arm_GridParams,right_arm_GridParams,...
    left_arm_tzParams,right_arm_tzParams,...
    };
